### ISSUE TITLE
Replace Glow Item Frames with Item Display Entities in 1.19.4

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/Custom-Blocks-API#4]
When Minecraft 1.19.4 is fully released replace Glow Item Frames with Item Display Entities to Improve performance a little more.

- [x] Wait for Minecraft 1.19.4 to Release
- [x] Replace Glow Item Frames with Item Display Entities

**Comment by VoxelBill** [comment]
Completed in Release v1.2
